apiVersion: v1
kind: Service
metadata:
  name: finveritas-api
  namespace: finveritas
  labels:
    app: finveritas-api
spec:
  type: NodePort
  selector:
    app: finveritas-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
